# Generated by Django 4.1 on 2022-08-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0003_alter_county_options_alter_sub_county_options_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ChurchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('church_denomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='church.churchdenomination')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.town')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ChurchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DenominationLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.churchdenomination')),
                ('leader_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.leaderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchPastorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.churchitem')),
                ('pastor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.pastorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.churchitem')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='churchitem',
            name='members',
            field=models.ManyToManyField(through='church.ChurchMembership', to='profiles.userprofile'),
        ),
        migrations.AddField(
            model_name='churchitem',
            name='pastor',
            field=models.ManyToManyField(through='church.ChurchPastorship', to='profiles.pastorprofile'),
        ),
        migrations.AddField(
            model_name='churchdenomination',
            name='church_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='church.churchtype'),
        ),
        migrations.AddField(
            model_name='churchdenomination',
            name='head_quoters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.town'),
        ),
    ]
