# Generated by Django 4.1 on 2022-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_leaderprofile_options_and_more'),
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchdenomination',
            options={'ordering': ['title'], 'verbose_name': 'Denomination', 'verbose_name_plural': 'Denominations'},
        ),
        migrations.AlterModelOptions(
            name='churchitem',
            options={'ordering': ['title'], 'verbose_name': 'Church', 'verbose_name_plural': 'Churches'},
        ),
        migrations.AlterModelOptions(
            name='churchmembership',
            options={'ordering': ['created_on'], 'verbose_name': 'Church Membership', 'verbose_name_plural': 'Church Memberships'},
        ),
        migrations.AlterModelOptions(
            name='churchpastorship',
            options={'ordering': ['created_on'], 'verbose_name': 'Church Pastor', 'verbose_name_plural': 'Church Pastors'},
        ),
        migrations.AlterModelOptions(
            name='churchtype',
            options={'ordering': ['title'], 'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AlterModelOptions(
            name='denominationleadership',
            options={'ordering': ['created_on'], 'verbose_name': 'Denomination Leader', 'verbose_name_plural': 'Denomination Leaders'},
        ),
        migrations.AddField(
            model_name='churchdenomination',
            name='leader',
            field=models.ManyToManyField(through='church.DenominationLeadership', to='profiles.leaderprofile'),
        ),
    ]
