# Generated by Django 4.1 on 2022-08-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_alter_churchdenomination_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmembership',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='churchitem',
            name='church_denomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='churches', to='church.churchdenomination'),
        ),
    ]
