# Generated by Django 4.1 on 2022-08-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_town_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name'], 'verbose_name': 'County', 'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='sub_county',
            options={'ordering': ['name'], 'verbose_name': 'Sub_county', 'verbose_name_plural': 'Sub_counties'},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['name'], 'verbose_name': 'Town', 'verbose_name_plural': 'Towns'},
        ),
    ]
