# Generated by Django 4.1 on 2022-08-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderprofile',
            options={'ordering': ['created_on'], 'verbose_name': 'Denomination Leader', 'verbose_name_plural': 'Denomination Leaders'},
        ),
        migrations.AlterModelOptions(
            name='pastorprofile',
            options={'ordering': ['created_on'], 'verbose_name': 'Pastor', 'verbose_name_plural': 'Pastors'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['created_on'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
