# Generated by Django 4.1 on 2022-08-17 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_leaderprofile_profile_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pastorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='profile_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastorprofile',
            name='profile_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pastor_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
